version: "3.7"

services:
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./services/minio/data:/data
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    tty: true
  memcached: 
    image: memcached:latest
    restart: always
    container_name: memcached
    ports:
      - "11211:11211"
    