upload:
  key: AIzaSyCwldouyj4wqx88BMEDKyHlhgeBCLjvhp8

memcached:
  host: localhost
  port: 11211
  cache_timeout: 10m

mysql:
  host: localhost
  port: 3306
  user: admin
  password: admin123

minio:
  host: localhost
  port: 9000
  bucket_name: images
  access_key: admin
  secret_access_key: admin123
  use_ssl: false

async: false
cache_inmemory: false
upload_folder: uploads
