upload:
  key: AIzaSyCwldouyj4wqx88BMEDKyHlhgeBCLjvhp8

memcached:
  host: localhost
  port: 22122
  cache_timeout: 30m

minio:
  host: localhost
  port: 9000
  bucket_name: thumbnails
  access_key: admin
  secret_access_key: admin123
  use_ssl: false

grpc_loader:
  host: localhost
  port: 8001
