// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  entity

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Item ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Item ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Item *Item

func ( Response ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Response ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Response *Response

func ( SnippetData ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SnippetData ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SnippetData *SnippetData

func ( ThumbnailBody ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ThumbnailBody ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ThumbnailBody *ThumbnailBody

func ( ThumbnailType ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ThumbnailType ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ThumbnailType *ThumbnailType
